swagger: "2.0"
info:
    title: FRP Webconsole
    description: FRP Webconsole
    license:
        name: MIT
        url: https://github.com/woxQAQ/frp-webconsole/blob/main/LICENSE
    version: 1.0.0
host: localhost:8080
basePath: /api/v1
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /frp/release:
        get:
            tags:
                - frpc
            summary: ListFrpRelease frpc
            operationId: frpc#ListFrpRelease
            parameters:
                - name: os
                  in: query
                  description: OS
                  required: false
                  type: string
                - name: arch
                  in: query
                  description: Architecture
                  required: false
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/FrpRelease'
            schemes:
                - http
definitions:
    FrpAsset:
        title: FrpAsset
        type: object
        properties:
            download_url:
                type: string
                description: Download URL of asset
                example: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
            downloads:
                type: integer
                description: Downloads of asset
                example: 100
                format: int64
            name:
                type: string
                description: Name of asset
                example: frp_0.55.0_linux_arm64.tar.gz
            size:
                type: integer
                description: Size of asset
                example: 1024
                format: int64
        description: A asset of frp release
        example:
            download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
            downloads: 100
            name: frp_0.55.0_linux_arm64.tar.gz
            size: 1024
    FrpRelease:
        title: FrpRelease
        type: object
        properties:
            assets:
                type: array
                items:
                    $ref: '#/definitions/FrpAsset'
                description: Assets of release
                example:
                    - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                      downloads: 100
                      name: frp_0.55.0_linux_arm64.tar.gz
                      size: 1024
                    - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                      downloads: 100
                      name: frp_0.55.0_linux_arm64.tar.gz
                      size: 1024
            created_at:
                type: string
                description: Created at
                example: "1972-11-23T01:21:18Z"
                format: date-time
            tag_name:
                type: string
                description: Tag name of release
                example: v0.55.0
        description: A release of frp
        example:
            assets:
                - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                  downloads: 100
                  name: frp_0.55.0_linux_arm64.tar.gz
                  size: 1024
                - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                  downloads: 100
                  name: frp_0.55.0_linux_arm64.tar.gz
                  size: 1024
            created_at: "1974-12-23T00:47:00Z"
            tag_name: v0.55.0
