openapi: 3.0.3
info:
    title: FRP Webconsole
    description: FRP Webconsole
    license:
        name: MIT
        url: https://github.com/woxQAQ/frp-webconsole/blob/main/LICENSE
    version: 1.0.0
servers:
    - url: http://localhost:8080
paths:
    /api/v1/frp/release:
        get:
            tags:
                - frpc
            summary: ListFrpRelease frpc
            operationId: frpc#ListFrpRelease
            parameters:
                - name: os
                  in: query
                  description: OS
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: OS
                    example: Provident sed est.
                  example: Dolor et.
                - name: arch
                  in: query
                  description: Architecture
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Architecture
                    example: Voluptatem eius odio.
                  example: Quidem necessitatibus itaque.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/FrpRelease'
                                example:
                                    - assets:
                                        - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                                          downloads: 100
                                          name: frp_0.55.0_linux_arm64.tar.gz
                                          size: 1024
                                        - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                                          downloads: 100
                                          name: frp_0.55.0_linux_arm64.tar.gz
                                          size: 1024
                                      created_at: "2008-12-17T04:56:17Z"
                                      tag_name: v0.55.0
                                    - assets:
                                        - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                                          downloads: 100
                                          name: frp_0.55.0_linux_arm64.tar.gz
                                          size: 1024
                                        - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                                          downloads: 100
                                          name: frp_0.55.0_linux_arm64.tar.gz
                                          size: 1024
                                      created_at: "2008-12-17T04:56:17Z"
                                      tag_name: v0.55.0
                            example:
                                - assets:
                                    - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                                      downloads: 100
                                      name: frp_0.55.0_linux_arm64.tar.gz
                                      size: 1024
                                    - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                                      downloads: 100
                                      name: frp_0.55.0_linux_arm64.tar.gz
                                      size: 1024
                                  created_at: "2008-12-17T04:56:17Z"
                                  tag_name: v0.55.0
                                - assets:
                                    - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                                      downloads: 100
                                      name: frp_0.55.0_linux_arm64.tar.gz
                                      size: 1024
                                    - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                                      downloads: 100
                                      name: frp_0.55.0_linux_arm64.tar.gz
                                      size: 1024
                                  created_at: "2008-12-17T04:56:17Z"
                                  tag_name: v0.55.0
                                - assets:
                                    - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                                      downloads: 100
                                      name: frp_0.55.0_linux_arm64.tar.gz
                                      size: 1024
                                    - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                                      downloads: 100
                                      name: frp_0.55.0_linux_arm64.tar.gz
                                      size: 1024
                                  created_at: "2008-12-17T04:56:17Z"
                                  tag_name: v0.55.0
components:
    schemas:
        FrpAsset:
            type: object
            properties:
                download_url:
                    type: string
                    description: Download URL of asset
                    example: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                downloads:
                    type: integer
                    description: Downloads of asset
                    example: 100
                    format: int64
                name:
                    type: string
                    description: Name of asset
                    example: frp_0.55.0_linux_arm64.tar.gz
                size:
                    type: integer
                    description: Size of asset
                    example: 1024
                    format: int64
            description: A asset of frp release
            example:
                download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                downloads: 100
                name: frp_0.55.0_linux_arm64.tar.gz
                size: 1024
        FrpRelease:
            type: object
            properties:
                assets:
                    type: array
                    items:
                        $ref: '#/components/schemas/FrpAsset'
                    description: Assets of release
                    example:
                        - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                          downloads: 100
                          name: frp_0.55.0_linux_arm64.tar.gz
                          size: 1024
                        - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                          downloads: 100
                          name: frp_0.55.0_linux_arm64.tar.gz
                          size: 1024
                        - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                          downloads: 100
                          name: frp_0.55.0_linux_arm64.tar.gz
                          size: 1024
                created_at:
                    type: string
                    description: Created at
                    example: "1987-03-27T01:30:27Z"
                    format: date-time
                tag_name:
                    type: string
                    description: Tag name of release
                    example: v0.55.0
            description: A release of frp
            example:
                assets:
                    - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                      downloads: 100
                      name: frp_0.55.0_linux_arm64.tar.gz
                      size: 1024
                    - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                      downloads: 100
                      name: frp_0.55.0_linux_arm64.tar.gz
                      size: 1024
                    - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                      downloads: 100
                      name: frp_0.55.0_linux_arm64.tar.gz
                      size: 1024
                    - download_url: https://github.com/fatedier/frp/releases/download/v0.55.0/frp_0.55.0_linux_arm64.tar.gz
                      downloads: 100
                      name: frp_0.55.0_linux_arm64.tar.gz
                      size: 1024
                created_at: "2002-10-05T17:52:52Z"
                tag_name: v0.55.0
tags:
    - name: frpc
      description: FRP Webconsole
